### ISSUE TITLE
Using the driver with ibeo ECU

### ISSUE THREAD

**Issue by ghost** [SICKAG/sick_ldmrs_laser#8] opened 2018-01-17 12:45 UTC
We are using this driver very successfully with ibeo LUX laserscanners. Is it however possible to extend its functionality to work with the ibeo ECU as well? After sensor fusion in the ECU the data type is slighty different (0x2205 instead of 0x2202). Any hints pointing as to where/how we could implement this efficiently?

**Comment by mintar** [comment] 2018-01-18 09:58
The actual parsing is done by the libsick_ldmrs, which is used by this ROS wrapper. This seems to be the relevant line:

https://github.com/SICKAG/libsick_ldmrs/blob/7d6c83a3c745655591b8b5faffe40357eef9723f/src/devices/LuxBase.cpp#L1487

**Comment by melodynk** [comment] 2018-04-03 06:31
I also use this driver to initailize the IBEO LUX. It seems that it does not start-up the IBEO because the ethernet signal light does now blink at all.
Although there is no error happening(below figure) ,there is nothing information printed in the /cloud and /objects messages.
Could you give me some advice to handle this issue?Many thanks!
![screenshot from 2018-03-30 15-03-01](https://user-images.githubusercontent.com/37090372/38232947-8e595984-374b-11e8-97fe-bf78989b7a95.png)
![screenshot from 2018-03-30 15-03-30](https://user-images.githubusercontent.com/37090372/38232988-b2545794-374b-11e8-8dbf-d124ba63799d.png)

**Comment by melodynk** [comment] 2018-04-03 07:55
I also use this driver to initailize the IBEO LUX. It seems that it does not start-up the IBEO because the ethernet signal light does now blink at all.
Although there is no error happening(below figure) ,there is nothing information printed in the /cloud and /objects messages.
Could you give me some advice to handle this issue?Many thanks!
![qq 20180403155412](https://user-images.githubusercontent.com/37090372/38236646-6c43a050-3757-11e8-8240-1890cbaad9b3.jpg)
![qq 20180403155439](https://user-images.githubusercontent.com/37090372/38236655-72de2552-3757-11e8-81a1-1c273f96dbd7.jpg)

**Comment by mintar** [comment] 2018-04-03 09:52
Is the IP of the scanner correct (192.168.0.1)?

**Comment by melodynk** [comment] 2018-04-08 10:59
So it means that the IBEO is not necessarily the 192.168.0.1 IP address,right?

**Comment by mintar** [comment] 2018-04-09 09:17
At least for the SICK LD-MRS, 192.168.0.1 is the default. I don't know about the Ibeo Lux. Also, I don't know if you (or somebody else) has changed the IP; it's stored on the device. Just check (and change) it with the software that came with the scanner.

**Comment by sangych** [comment] 2018-07-03 10:10
@mintar Hi, when I used this driver with a ibeo LUX, it caused error like this. Could you please see what's the issue? I was sure that the ip connection was right because the ILV shown the connection
![sick_error](https://user-images.githubusercontent.com/7802555/42213589-cbdaab90-7eeb-11e8-8f13-0095b6ab9f71.png)

**Comment by jspricke** [comment] 2018-07-03 10:57
https://answers.ros.org/question/209452/exception-thrown-while-processing-service-call-time-is-out-of-dual-32-bit-range/

We have a number of places where we use the time. @sangych are you able to adopt the code as written above?

**Comment by mintar** [comment] 2018-07-03 11:11
I'm pretty sure the problem is in these lines:

https://github.com/SICKAG/sick_ldmrs_laser/blob/273ee5312df930581e4ca0187e672a6e8d87711c/sick_ldmrs_driver/src/sick_ldmrs_node.cpp#L276-L277

My guess is that `ros::Time::now()` is 0, thus subtracting something from it makes it negative, so the exception is thrown.

@sangych : You probably have set the parameter `use_sim_time` to `true`. When you use this driver, the parameter must be set to `false`:

```
rosparam set use_sim_time false
```

However, your problem has nothing to do with this issue. If the command above doesn't fix your issue, please open a new issue for this.

Closing this issue since the original problem seems to be resolved.

**Closed by mintar** 2018-07-03 11:11 UTC

**Comment by sangych** [comment] 2018-07-04 02:01
According to your solution, the problem I faced was sovled. Thanks! @mintar
